sudo: required
services: docker
language: minimal
branches:
  only:
  - master
script:
  - docker build --pull -t "bsycorp/system-tools:1.0.$TRAVIS_BUILD_NUMBER" -t "bsycorp/system-tools:latest" .
  - docker login -u $DOCKERUSER -p $DOCKERPASS
  - docker push bsycorp/system-tools
